### ISSUE TITLE
Question about random forest classification

### ISSUE THREAD

**Issue by zoink** [kykiefer/depression-detect#4]
Let's say after segmenting an audio wav file:

You do short-term feature extraction and end up with 20 50ms frames with 34 features each. This would yield a feature matrix of [20 x 34]. 

Would you end up extracting a [20 x 34] matrix for each patient in the dataset? If so, how do you make sure each patient has feature matrices of equal length (i.e. [N x 34] feature matrices where N is constant for all M patients) after audio segmentation? Are you just using the entire audio clip and treating silences as 0s? Thanks so much!

**Comment by kykiefer** [comment]
The initial segmentation is aimed at removing the silence. On the remaining (non-silent) audio you can go about extracting features for each patient.

If you want to make sure you're getting an equal numbers of samples from each patient, you could constrain on the shortest audio clip for a patient. For example, if the shortest audio clip (post-segmentation) is 5,000ms, using 50ms frames, you could extract 100 frames for each patient. I wouldn't necessarily advise this because you'd be throwing away a lot of valuable data for model training. But it's a viable approach if you're concerned about balancing training data amongst participants.
